USE [master]
GO

CREATE DATABASE [AV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AV', FILENAME = N'd:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\AV.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AV_log', FILENAME = N'd:\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\AV_log.ldf' , SIZE = 4096KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [AV] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AV] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AV] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AV] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AV] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AV] SET ARITHABORT OFF 
GO
ALTER DATABASE [AV] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AV] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [AV] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AV] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AV] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AV] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AV] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AV] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AV] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AV] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AV] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AV] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AV] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AV] SET RECOVERY FULL 
GO
ALTER DATABASE [AV] SET  MULTI_USER 
GO
ALTER DATABASE [AV] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AV] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AV] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AV', N'ON'
GO
USE [AV]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[DeleteAlbum]
 @id INT
AS

DELETE FROM Albums
WHERE id = @id


GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[DeletePh]
 @id INT
AS

DELETE FROM Phs
WHERE id = @id
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[GetAlbums] AS
SELECT id, [name], [description]
FROM Albums
ORDER BY [name]


GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GetPh] 
	@id INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT [name], ISNULL([description], '') AS description, Ph 
	FROM Phs 
	WHERE id = @id

END

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE proc [dbo].[GetPhsByAlbum]
	@albumId INT
AS

SELECT id, [name], ISNULL([description], '') AS [description], [Ph]
FROM Phs
WHERE [album_id] = @albumId

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[InsertAlbum]
	@name AS NVARCHAR(20),
	@desc NVARCHAR(200)
 AS

INSERT INTO Albums ([name], [description]) 
VALUES (@name, @desc) 

RETURN SCOPE_IDENTITY()


GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[InsertPh]
	@name AS NVARCHAR(50),
	@desc AS NVARCHAR(200) = null,
	@Ph AS VARBINARY(MAX),
	@albumId AS INT
 AS

INSERT INTO Phs ([name], [description], Ph, album_id) 
VALUES (@name, @desc, @Ph, @albumId) 

RETURN SCOPE_IDENTITY()



GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[UpdateAlbum]
	@id INT,
	@name AS NVARCHAR(20),
	@desc NVARCHAR(200)

AS

UPDATE Albums
SET name = @name, [description] = @desc
WHERE id = @id

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[UpdatePh]
	@id INT,
	@name AS NVARCHAR(20),
	@desc NVARCHAR(200)

AS

UPDATE Phs
SET name = @name, [description] = @desc
WHERE id = @id

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Albums](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[description] [nvarchar](200) NULL,
 CONSTRAINT [PK_Albums] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Phs](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[description] [nvarchar](200) NULL,
	[album_id] [int] NOT NULL,
	[Ph] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_Phs] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Phs]  WITH CHECK ADD  CONSTRAINT [FK_Albums_Phs] FOREIGN KEY([album_id])
REFERENCES [dbo].[Albums] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Phs] CHECK CONSTRAINT [FK_Albums_Phs]
GO
USE [master]
GO
ALTER DATABASE [AV] SET  READ_WRITE 
GO
