//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AV
{
    using System;
    using System.Collections.Generic;
    
    public partial class dup_ph
    {
        public long pkey { get; set; }
        public string id { get; set; }
        public string path { get; set; }
    
        public virtual ph ph { get; set; }
    }
}
