//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph
    {
        public string id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte[] photo { get; set; }
        public string path { get; set; }
        public Nullable<System.DateTimeOffset> time_stamp { get; set; }
        public string infoTags { get; set; }
        public long pKey { get; set; }
        public Nullable<bool> is_dup { get; set; }
    }
}
